apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-labels
  annotations:
    policies.kyverno.io/title: RollingUpdate
    policies.kyverno.io/category: Sample
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: RollingUpdate
    policies.kyverno.io/description: >-
      Rolling Update.      
spec:
  rules:
  - name: rolling-update
    match:
      resources:
        kinds:
        - Deployment
    mutate:
      patchStrategicMerge:
        strategy:
          type: RollingUpdate
          rollingUpdate:
            maxUnavailable: 25%
            maxSurge: 75%
